### ISSUE TITLE
Blockquote's vertical bar placement within forums

### ISSUE THREAD

**Issue by JTSobie** [CryptonZylog/uetrip#3]
Minor issue:  The vertical bar is placed to the left of the poster's avatar image and name instead of immediately left of the quoted text.
In the UETrip color scheme, the feed uses a lighter, more noticeable color for the vertical bar, as opposed to in the forum where it is a dark color and less noticable.

![](http://i1352.photobucket.com/albums/q654/Cryptid_JT/GitHub/UETrip%20quote%20issue_zpsjlz5vdbg.jpg)

**Comment by CryptonZylog** [comment]
So I think a better idea would be to restructure post layout a bit.

Have the post body be the first thing that hits the eye of the reader (since it's most relevant).

The authorship of the post and some link buttons can go below.

It could look something like this (please excuse the crude drawing).

![](http://i.imgur.com/NrY1Wq2.png)

**Comment by JTSobie** [comment]
Perhaps in keeping with the original position of the avatar, the text can be in a different table column?
I guess above or below would be better for narrower screens (phone browsers).

![suggestion](https://i1352.photobucket.com/albums/q654/Cryptid_JT/GitHub/suggested%20post_zps3aflm1em.png)

**Comment by CryptonZylog** [comment]
Sounds good. It's two separate divs in a grid pattern. I can make the avatar collapse under the post body.
